server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://rm-2zewws6e31p267bksro.mysql.rds.aliyuncs.com:3306/ethcdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ethcdb
    password: Zz112211
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zh.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:/system/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
logging:
  level:
    com.zh.eth.mapper: debug